import type { GenreStyle, VocalCharacter, VocalStyleParams } from "@/types/vocalStyle";

/**
 * Starting points, not clones. Genre-inspired presets capture production
 * *characteristics* the brief described (tonality, aggression, presence,
 * saturation, ambiance, dynamics) — never a literal copy of any artist's
 * or plugin's actual chain, which we have no access to and wouldn't use
 * even if we did. Every value here is hand-picked to be internally
 * differentiated, not reverse-engineered from a reference track.
 */
export const VOCAL_CHARACTER_PRESETS: Record<VocalCharacter, VocalStyleParams> = {
  clean: {
    label: "Limpio",
    description: "Forma mínima — corrige problemas, no agrega carácter.",
    eqTiltDb: 0,
    presenceBoostDb: 0,
    saturationDriveDb: 0,
    saturationTone: "neutral",
    saturationMix: 0,
    compressionRatio: 2,
    reverbMix: 0.05,
    reverbSize: "room",
    delayMix: 0,
  },
  natural: {
    label: "Natural",
    description: "Un poco de cohesión y calidez, nada evidente.",
    eqTiltDb: 0,
    presenceBoostDb: 1,
    saturationDriveDb: 2,
    saturationTone: "neutral",
    saturationMix: 0.15,
    compressionRatio: 2.5,
    reverbMix: 0.12,
    reverbSize: "room",
    delayMix: 0,
  },
  bright: {
    label: "Brillante",
    description: "Agudos realzados, presente y nítido.",
    eqTiltDb: 3,
    presenceBoostDb: 3,
    saturationDriveDb: 3,
    saturationTone: "bright",
    saturationMix: 0.25,
    compressionRatio: 3,
    reverbMix: 0.15,
    reverbSize: "plate",
    delayMix: 0.05,
  },
  dark: {
    label: "Oscuro",
    description: "Graves al frente, agudos redondeados, con ambiente sombrío.",
    eqTiltDb: -3,
    presenceBoostDb: 0,
    saturationDriveDb: 4,
    saturationTone: "warm",
    saturationMix: 0.3,
    compressionRatio: 3,
    reverbMix: 0.2,
    reverbSize: "hall",
    delayMix: 0.1,
  },
  aggressive: {
    label: "Agresivo",
    description: "Duro, al frente, muy saturado.",
    eqTiltDb: 2,
    presenceBoostDb: 4,
    saturationDriveDb: 8,
    saturationTone: "bright",
    saturationMix: 0.45,
    compressionRatio: 5,
    reverbMix: 0.1,
    reverbSize: "room",
    delayMix: 0,
  },
  melodic: {
    label: "Melódico",
    description: "Suave, cálido, se acomoda en la mezcla con espacio.",
    eqTiltDb: 1,
    presenceBoostDb: 2,
    saturationDriveDb: 3,
    saturationTone: "warm",
    saturationMix: 0.2,
    compressionRatio: 3,
    reverbMix: 0.3,
    reverbSize: "hall",
    delayMix: 0.2,
  },
  trap: {
    label: "Trap",
    description: "Brillante, ajustado, con un poco de textura.",
    eqTiltDb: 2,
    presenceBoostDb: 3,
    saturationDriveDb: 5,
    saturationTone: "bright",
    saturationMix: 0.3,
    compressionRatio: 4,
    reverbMix: 0.15,
    reverbSize: "plate",
    delayMix: 0.15,
  },
  rage: {
    label: "Rage",
    description: "Máxima saturación y presencia, directo a la cara.",
    eqTiltDb: 3,
    presenceBoostDb: 5,
    saturationDriveDb: 10,
    saturationTone: "bright",
    saturationMix: 0.55,
    compressionRatio: 6,
    reverbMix: 0.2,
    reverbSize: "hall",
    delayMix: 0.2,
  },
  cinematic: {
    label: "Cinemático",
    description: "Amplio, espacioso, cola dramática.",
    eqTiltDb: -1,
    presenceBoostDb: 1,
    saturationDriveDb: 2,
    saturationTone: "warm",
    saturationMix: 0.15,
    compressionRatio: 2.5,
    reverbMix: 0.4,
    reverbSize: "hall",
    delayMix: 0.25,
  },
  radio: {
    label: "Radio",
    description: "Al frente, consistente, listo para sonar fuerte.",
    eqTiltDb: 2,
    presenceBoostDb: 4,
    saturationDriveDb: 4,
    saturationTone: "neutral",
    saturationMix: 0.25,
    compressionRatio: 5,
    reverbMix: 0.08,
    reverbSize: "room",
    delayMix: 0,
  },
  lead: {
    label: "Principal",
    description: "Claro y al frente — construido para ir arriba de todo.",
    eqTiltDb: 1,
    presenceBoostDb: 4,
    saturationDriveDb: 3,
    saturationTone: "neutral",
    saturationMix: 0.2,
    compressionRatio: 3.5,
    reverbMix: 0.15,
    reverbSize: "room",
    delayMix: 0.05,
  },
  adlib: {
    label: "Ad-lib",
    description: "Aéreo y amplio con una cola más larga, se ubica detrás de la voz principal.",
    eqTiltDb: 2,
    presenceBoostDb: 3,
    saturationDriveDb: 4,
    saturationTone: "bright",
    saturationMix: 0.3,
    compressionRatio: 3,
    reverbMix: 0.35,
    reverbSize: "plate",
    delayMix: 0.3,
  },
  double: {
    label: "Doblaje",
    description: "Sutil y discreto — pensado para reforzar la voz principal, no competir con ella.",
    eqTiltDb: 0,
    presenceBoostDb: 2,
    saturationDriveDb: 2,
    saturationTone: "neutral",
    saturationMix: 0.15,
    compressionRatio: 2.5,
    reverbMix: 0.1,
    reverbSize: "room",
    delayMix: 0.1,
  },
};

export const GENRE_STYLE_PRESETS: Record<GenreStyle, VocalStyleParams> = {
  rageStyle: {
    label: "Inspirado en rage",
    description: "Muy agresivo, muy saturado, brillante y con limitación dura.",
    eqTiltDb: 3,
    presenceBoostDb: 5,
    saturationDriveDb: 12,
    saturationTone: "bright",
    saturationMix: 0.6,
    compressionRatio: 6,
    reverbMix: 0.25,
    reverbSize: "hall",
    delayMix: 0.15,
  },
  atmosphericTrap: {
    label: "Inspirado en trap atmosférico",
    description: "Oscuro, espacioso, mucha reverb y delay, saturación cálida.",
    eqTiltDb: -2,
    presenceBoostDb: 1,
    saturationDriveDb: 3,
    saturationTone: "warm",
    saturationMix: 0.2,
    compressionRatio: 3,
    reverbMix: 0.45,
    reverbSize: "hall",
    delayMix: 0.35,
  },
  experimentalUrban: {
    label: "Inspirado en urbano experimental",
    description: "Texturizado y brillante, carácter de saturación distintivo.",
    eqTiltDb: 1,
    presenceBoostDb: 2,
    saturationDriveDb: 6,
    saturationTone: "bright",
    saturationMix: 0.35,
    compressionRatio: 4,
    reverbMix: 0.2,
    reverbSize: "plate",
    delayMix: 0.15,
  },
  darkCinematicUrban: {
    label: "Inspirado en urbano cinemático oscuro",
    description: "Oscuro, amplio, mucha reverb atmosférica.",
    eqTiltDb: -3,
    presenceBoostDb: 0,
    saturationDriveDb: 4,
    saturationTone: "warm",
    saturationMix: 0.25,
    compressionRatio: 3,
    reverbMix: 0.5,
    reverbSize: "hall",
    delayMix: 0.2,
  },
  aggressiveUrban: {
    label: "Inspirado en urbano agresivo",
    description: "Contundente, al frente, muy saturado.",
    eqTiltDb: 2,
    presenceBoostDb: 4,
    saturationDriveDb: 9,
    saturationTone: "bright",
    saturationMix: 0.5,
    compressionRatio: 5.5,
    reverbMix: 0.12,
    reverbSize: "room",
    delayMix: 0.1,
  },
  hardUrban: {
    label: "Inspirado en urbano duro",
    description: "Contundente y ajustado, presente sin mucho ambiente.",
    eqTiltDb: 2,
    presenceBoostDb: 3,
    saturationDriveDb: 7,
    saturationTone: "bright",
    saturationMix: 0.4,
    compressionRatio: 5,
    reverbMix: 0.1,
    reverbSize: "room",
    delayMix: 0.05,
  },
  modernLatinUrban: {
    label: "Inspirado en urbano latino moderno",
    description: "Limpio y presente con calidez melódica.",
    eqTiltDb: 1,
    presenceBoostDb: 3,
    saturationDriveDb: 2,
    saturationTone: "neutral",
    saturationMix: 0.15,
    compressionRatio: 3,
    reverbMix: 0.2,
    reverbSize: "plate",
    delayMix: 0.2,
  },
  darkMelodicUrban: {
    label: "Inspirado en urbano melódico oscuro",
    description: "Oscuro y sombrío con una cola melódica y espaciosa.",
    eqTiltDb: -2,
    presenceBoostDb: 1,
    saturationDriveDb: 3,
    saturationTone: "warm",
    saturationMix: 0.25,
    compressionRatio: 3,
    reverbMix: 0.35,
    reverbSize: "hall",
    delayMix: 0.25,
  },
};
