import type { GenreStyle, VocalCharacter, VocalStyleParams } from "@/types/vocalStyle";

/**
 * Starting points, not clones. Genre-inspired presets capture production
 * *characteristics* the brief described (tonality, aggression, presence,
 * saturation, ambiance, dynamics) — never a literal copy of any artist's
 * or plugin's actual chain, which we have no access to and wouldn't use
 * even if we did. Every value here is hand-picked to be internally
 * differentiated, not reverse-engineered from a reference track.
 */
export const VOCAL_CHARACTER_PRESETS: Record<VocalCharacter, VocalStyleParams> = {
  clean: {
    label: "Clean",
    description: "Minimal shaping — correct problems, don't add character.",
    eqTiltDb: 0,
    presenceBoostDb: 0,
    saturationDriveDb: 0,
    saturationTone: "neutral",
    saturationMix: 0,
    compressionRatio: 2,
    reverbMix: 0.05,
    reverbSize: "room",
    delayMix: 0,
  },
  natural: {
    label: "Natural",
    description: "A little glue and warmth, nothing obvious.",
    eqTiltDb: 0,
    presenceBoostDb: 1,
    saturationDriveDb: 2,
    saturationTone: "neutral",
    saturationMix: 0.15,
    compressionRatio: 2.5,
    reverbMix: 0.12,
    reverbSize: "room",
    delayMix: 0,
  },
  bright: {
    label: "Bright",
    description: "Lifted top end, present and crisp.",
    eqTiltDb: 3,
    presenceBoostDb: 3,
    saturationDriveDb: 3,
    saturationTone: "bright",
    saturationMix: 0.25,
    compressionRatio: 3,
    reverbMix: 0.15,
    reverbSize: "plate",
    delayMix: 0.05,
  },
  dark: {
    label: "Dark",
    description: "Bass-forward, rounded top end, moody.",
    eqTiltDb: -3,
    presenceBoostDb: 0,
    saturationDriveDb: 4,
    saturationTone: "warm",
    saturationMix: 0.3,
    compressionRatio: 3,
    reverbMix: 0.2,
    reverbSize: "hall",
    delayMix: 0.1,
  },
  aggressive: {
    label: "Aggressive",
    description: "Hard, forward, heavily driven.",
    eqTiltDb: 2,
    presenceBoostDb: 4,
    saturationDriveDb: 8,
    saturationTone: "bright",
    saturationMix: 0.45,
    compressionRatio: 5,
    reverbMix: 0.1,
    reverbSize: "room",
    delayMix: 0,
  },
  melodic: {
    label: "Melodic",
    description: "Smooth, warm, sits inside the mix with space.",
    eqTiltDb: 1,
    presenceBoostDb: 2,
    saturationDriveDb: 3,
    saturationTone: "warm",
    saturationMix: 0.2,
    compressionRatio: 3,
    reverbMix: 0.3,
    reverbSize: "hall",
    delayMix: 0.2,
  },
  trap: {
    label: "Trap",
    description: "Bright, tight, a bit of grit.",
    eqTiltDb: 2,
    presenceBoostDb: 3,
    saturationDriveDb: 5,
    saturationTone: "bright",
    saturationMix: 0.3,
    compressionRatio: 4,
    reverbMix: 0.15,
    reverbSize: "plate",
    delayMix: 0.15,
  },
  rage: {
    label: "Rage",
    description: "Maximum drive and presence, in-your-face.",
    eqTiltDb: 3,
    presenceBoostDb: 5,
    saturationDriveDb: 10,
    saturationTone: "bright",
    saturationMix: 0.55,
    compressionRatio: 6,
    reverbMix: 0.2,
    reverbSize: "hall",
    delayMix: 0.2,
  },
  cinematic: {
    label: "Cinematic",
    description: "Wide, spacious, dramatic tail.",
    eqTiltDb: -1,
    presenceBoostDb: 1,
    saturationDriveDb: 2,
    saturationTone: "warm",
    saturationMix: 0.15,
    compressionRatio: 2.5,
    reverbMix: 0.4,
    reverbSize: "hall",
    delayMix: 0.25,
  },
  radio: {
    label: "Radio",
    description: "Forward, consistent, loud-ready.",
    eqTiltDb: 2,
    presenceBoostDb: 4,
    saturationDriveDb: 4,
    saturationTone: "neutral",
    saturationMix: 0.25,
    compressionRatio: 5,
    reverbMix: 0.08,
    reverbSize: "room",
    delayMix: 0,
  },
  lead: {
    label: "Lead",
    description: "Clear and forward — built to sit on top.",
    eqTiltDb: 1,
    presenceBoostDb: 4,
    saturationDriveDb: 3,
    saturationTone: "neutral",
    saturationMix: 0.2,
    compressionRatio: 3.5,
    reverbMix: 0.15,
    reverbSize: "room",
    delayMix: 0.05,
  },
  adlib: {
    label: "Adlib",
    description: "Airy and wide with a longer tail, sits behind the lead.",
    eqTiltDb: 2,
    presenceBoostDb: 3,
    saturationDriveDb: 4,
    saturationTone: "bright",
    saturationMix: 0.3,
    compressionRatio: 3,
    reverbMix: 0.35,
    reverbSize: "plate",
    delayMix: 0.3,
  },
  double: {
    label: "Double",
    description: "Subtle and tucked — meant to reinforce a lead, not compete.",
    eqTiltDb: 0,
    presenceBoostDb: 2,
    saturationDriveDb: 2,
    saturationTone: "neutral",
    saturationMix: 0.15,
    compressionRatio: 2.5,
    reverbMix: 0.1,
    reverbSize: "room",
    delayMix: 0.1,
  },
};

export const GENRE_STYLE_PRESETS: Record<GenreStyle, VocalStyleParams> = {
  rageStyle: {
    label: "Rage-inspired",
    description: "Very aggressive, heavily saturated, bright and hard-limited.",
    eqTiltDb: 3,
    presenceBoostDb: 5,
    saturationDriveDb: 12,
    saturationTone: "bright",
    saturationMix: 0.6,
    compressionRatio: 6,
    reverbMix: 0.25,
    reverbSize: "hall",
    delayMix: 0.15,
  },
  atmosphericTrap: {
    label: "Atmospheric trap-inspired",
    description: "Dark, spacious, heavy reverb and delay, warm saturation.",
    eqTiltDb: -2,
    presenceBoostDb: 1,
    saturationDriveDb: 3,
    saturationTone: "warm",
    saturationMix: 0.2,
    compressionRatio: 3,
    reverbMix: 0.45,
    reverbSize: "hall",
    delayMix: 0.35,
  },
  experimentalUrban: {
    label: "Experimental urban-inspired",
    description: "Textured and bright, distinctive saturation character.",
    eqTiltDb: 1,
    presenceBoostDb: 2,
    saturationDriveDb: 6,
    saturationTone: "bright",
    saturationMix: 0.35,
    compressionRatio: 4,
    reverbMix: 0.2,
    reverbSize: "plate",
    delayMix: 0.15,
  },
  darkCinematicUrban: {
    label: "Dark cinematic urban-inspired",
    description: "Dark, wide, heavy atmospheric reverb.",
    eqTiltDb: -3,
    presenceBoostDb: 0,
    saturationDriveDb: 4,
    saturationTone: "warm",
    saturationMix: 0.25,
    compressionRatio: 3,
    reverbMix: 0.5,
    reverbSize: "hall",
    delayMix: 0.2,
  },
  aggressiveUrban: {
    label: "Aggressive urban-inspired",
    description: "Hard-hitting, forward, heavily driven.",
    eqTiltDb: 2,
    presenceBoostDb: 4,
    saturationDriveDb: 9,
    saturationTone: "bright",
    saturationMix: 0.5,
    compressionRatio: 5.5,
    reverbMix: 0.12,
    reverbSize: "room",
    delayMix: 0.1,
  },
  hardUrban: {
    label: "Hard urban-inspired",
    description: "Punchy and tight, present without much ambiance.",
    eqTiltDb: 2,
    presenceBoostDb: 3,
    saturationDriveDb: 7,
    saturationTone: "bright",
    saturationMix: 0.4,
    compressionRatio: 5,
    reverbMix: 0.1,
    reverbSize: "room",
    delayMix: 0.05,
  },
  modernLatinUrban: {
    label: "Modern Latin urban-inspired",
    description: "Clean and present with melodic warmth.",
    eqTiltDb: 1,
    presenceBoostDb: 3,
    saturationDriveDb: 2,
    saturationTone: "neutral",
    saturationMix: 0.15,
    compressionRatio: 3,
    reverbMix: 0.2,
    reverbSize: "plate",
    delayMix: 0.2,
  },
  darkMelodicUrban: {
    label: "Dark melodic urban-inspired",
    description: "Dark and moody with a melodic, spacious tail.",
    eqTiltDb: -2,
    presenceBoostDb: 1,
    saturationDriveDb: 3,
    saturationTone: "warm",
    saturationMix: 0.25,
    compressionRatio: 3,
    reverbMix: 0.35,
    reverbSize: "hall",
    delayMix: 0.25,
  },
};
